// src/app/layout.tsx
import clsx from 'clsx';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import localFont from 'next/font/local';
import { JSX, ReactNode } from 'react';
import { QueryProvider } from 'shared/query/query-provider'; // Импортируем ваш QueryProvider
import '../shared/styles/globals.scss';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600'],
  display: 'swap',
});

const sfPro = localFont({
  src: [{ path: '../fonts/sf-pro/SFProDisplay-Bold.woff2', weight: '1000', style: 'normal' }],
  variable: '--font-sf-pro',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={clsx(roboto.variable, sfPro.variable)}>
        <QueryProvider>
          {' '}
          {/* Оборачиваем children в QueryProvider */}
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
