const now = Math.floor(Date.now() / 1000);

export const CONTACTS_PAGE_1 = {
  count: 20,
  next: '/api/v1/contact/messenger-list/?page=2&page_size=5',
  previous: null,
  results: [
    {
      uid: '1',
      owner_user: '1',
      system_contact: {
        uid: '1',
        avatar: 'avatar-1.svg',
        avatar_url: '/images/avatars/avatar-1.svg',
        avatar_webp: 'avatar-1.webp',
        avatar_webp_url: '/images/avatars/avatar-1.webp',
        is_online: true,
        was_online_at: 0,
      },
      first_name: 'Влад',
      last_name: 'Ляшев',
      phone: '+79990000001',
    },
    {
      uid: '2',
      owner_user: '2',
      system_contact: {
        uid: '2',
        avatar: 'avatar-2.svg',
        avatar_url: '/images/avatars/avatar-2.svg',
        avatar_webp: 'avatar-2.webp',
        avatar_webp_url: '/images/avatars/avatar-2.webp',
        is_online: false,
        was_online_at: now - 30,
      },
      first_name: 'Анна',
      last_name: 'Киреева',
      phone: '+79990000002',
    },
    {
      uid: '3',
      owner_user: '3',
      system_contact: {
        uid: '3',
        avatar: 'avatar-3.svg',
        avatar_url: '/images/avatars/avatar-3.svg',
        avatar_webp: 'avatar-3.webp',
        avatar_webp_url: '/images/avatars/avatar-3.webp',
        is_online: false,
        was_online_at: now - 5 * 60,
      },
      first_name: 'Максим',
      last_name: 'Орлов',
      phone: '+79990000003',
    },
    {
      uid: '4',
      owner_user: '4',
      system_contact: {
        uid: '4',
        avatar: 'avatar-4.svg',
        avatar_url: '/images/avatars/avatar-4.svg',
        avatar_webp: 'avatar-4.webp',
        avatar_webp_url: '/images/avatars/avatar-4.webp',
        is_online: false,
        was_online_at: now - 18 * 60,
      },
      first_name: 'Екатерина',
      last_name: 'Христорождественнская',
      phone: '+79990000004',
    },
    {
      uid: '5',
      owner_user: '5',
      system_contact: {
        uid: '5',
        avatar: 'avatar-5.svg',
        avatar_url: '/images/avatars/avatar-5.svg',
        avatar_webp: 'avatar-5.webp',
        avatar_webp_url: '/images/avatars/avatar-5.webp',
        is_online: false,
        was_online_at: now - 42 * 60,
      },
      first_name: 'Илья',
      last_name: 'Романов',
      phone: '+79990000005',
    },
  ],
};

export const CONTACTS_PAGE_2 = {
  count: 20,
  next: '/api/v1/contact/messenger-list/?page=3&page_size=5',
  previous: '/api/v1/contact/messenger-list/?page=1&page_size=5',
  results: [
    {
      uid: '6',
      owner_user: '6',
      system_contact: {
        uid: '6',
        avatar: 'avatar-1.svg',
        avatar_url: '/images/avatars/avatar-1.svg',
        avatar_webp: 'avatar-1.webp',
        avatar_webp_url: '/images/avatars/avatar-1.webp',
        is_online: false,
        was_online_at: now - 3600,
      },
      first_name: 'Мария',
      last_name: 'Соколова',
      phone: '+79990000006',
    },
    {
      uid: '7',
      owner_user: '7',
      system_contact: {
        uid: '7',
        avatar: 'avatar-2.svg',
        avatar_url: '/images/avatars/avatar-2.svg',
        avatar_webp: 'avatar-2.webp',
        avatar_webp_url: '/images/avatars/avatar-2.webp',
        is_online: false,
        was_online_at: now - 2 * 3600,
      },
      first_name: 'Артём',
      last_name: 'Кузнецов',
      phone: '+79990000007',
    },
    {
      uid: '8',
      owner_user: '8',
      system_contact: {
        uid: '8',
        avatar: 'avatar-3.svg',
        avatar_url: '/images/avatars/avatar-3.svg',
        avatar_webp: 'avatar-3.webp',
        avatar_webp_url: '/images/avatars/avatar-3.webp',
        is_online: false,
        was_online_at: now - 5 * 3600,
      },
      first_name: 'Ольга',
      last_name: 'Павлова',
      phone: '+79990000008',
    },
    {
      uid: '9',
      owner_user: '9',
      system_contact: {
        uid: '9',
        avatar: 'avatar-4.svg',
        avatar_url: '/images/avatars/avatar-4.svg',
        avatar_webp: 'avatar-4.webp',
        avatar_webp_url: '/images/avatars/avatar-4.webp',
        is_online: false,
        was_online_at: now - 12 * 3600,
      },
      first_name: 'Денис',
      last_name: 'Фёдоров',
      phone: '+79990000009',
    },
    {
      uid: '10',
      owner_user: '10',
      system_contact: {
        uid: '10',
        avatar: 'avatar-5.svg',
        avatar_url: '/images/avatars/avatar-5.svg',
        avatar_webp: 'avatar-5.webp',
        avatar_webp_url: '/images/avatars/avatar-5.webp',
        is_online: false,
        was_online_at: now - 23 * 3600,
      },
      first_name: 'Наталья',
      last_name: 'Иванова',
      phone: '+79990000010',
    },
  ],
};

export const CONTACTS_PAGE_3 = {
  count: 20,
  next: '/api/v1/contact/messenger-list/?page=4&page_size=5',
  previous: '/api/v1/contact/messenger-list/?page=2&page_size=5',
  results: [
    {
      uid: '11',
      owner_user: '11',
      system_contact: {
        uid: '11',
        avatar: 'avatar-1.svg',
        avatar_url: '/images/avatars/avatar-1.svg',
        avatar_webp: 'avatar-1.webp',
        avatar_webp_url: '/images/avatars/avatar-1.webp',
        is_online: false,
        was_online_at: now - 24 * 3600,
      },
      first_name: 'Павел',
      last_name: 'Мельников',
      phone: '+79990000011',
    },
    {
      uid: '12',
      owner_user: '12',
      system_contact: {
        uid: '12',
        avatar: 'avatar-2.svg',
        avatar_url: '/images/avatars/avatar-2.svg',
        avatar_webp: 'avatar-2.webp',
        avatar_webp_url: '/images/avatars/avatar-2.webp',
        is_online: false,
        was_online_at: now - 30 * 3600,
      },
      first_name: 'Юлия',
      last_name: 'Захарова',
      phone: '+79990000012',
    },
    {
      uid: '13',
      owner_user: '13',
      system_contact: {
        uid: '13',
        avatar: 'avatar-3.svg',
        avatar_url: '/images/avatars/avatar-3.svg',
        avatar_webp: 'avatar-3.webp',
        avatar_webp_url: '/images/avatars/avatar-3.webp',
        is_online: false,
        was_online_at: now - 2 * 86400,
      },
      first_name: 'Сергей',
      last_name: 'Белов',
      phone: '+79990000013',
    },
    {
      uid: '14',
      owner_user: '14',
      system_contact: {
        uid: '14',
        avatar: 'avatar-4.svg',
        avatar_url: '/images/avatars/avatar-4.svg',
        avatar_webp: 'avatar-4.webp',
        avatar_webp_url: '/images/avatars/avatar-4.webp',
        is_online: false,
        was_online_at: now - 3 * 86400,
      },
      first_name: 'Алина',
      last_name: 'Волкова',
      phone: '+79990000014',
    },
    {
      uid: '15',
      owner_user: '15',
      system_contact: {
        uid: '15',
        avatar: 'avatar-5.svg',
        avatar_url: '/images/avatars/avatar-5.svg',
        avatar_webp: 'avatar-5.webp',
        avatar_webp_url: '/images/avatars/avatar-5.webp',
        is_online: false,
        was_online_at: now - 5 * 86400,
      },
      first_name: 'Роман',
      last_name: 'Гусев',
      phone: '+79990000015',
    },
  ],
};

export const CONTACTS_PAGE_4 = {
  count: 20,
  next: null,
  previous: '/api/v1/contact/messenger-list/?page=3&page_size=5',
  results: [
    {
      uid: '16',
      owner_user: '16',
      system_contact: {
        uid: '16',
        avatar: 'avatar-1.svg',
        avatar_url: '/images/avatars/avatar-1.svg',
        avatar_webp: 'avatar-1.webp',
        avatar_webp_url: '/images/avatars/avatar-1.webp',
        is_online: false,
        was_online_at: now - 7 * 86400,
      },
      first_name: 'Елена',
      last_name: 'Калинина',
      phone: '+79990000016',
    },
    {
      uid: '17',
      owner_user: '17',
      system_contact: {
        uid: '17',
        avatar: 'avatar-2.svg',
        avatar_url: '/images/avatars/avatar-2.svg',
        avatar_webp: 'avatar-2.webp',
        avatar_webp_url: '/images/avatars/avatar-2.webp',
        is_online: false,
        was_online_at: now - 10 * 86400,
      },
      first_name: 'Алексей',
      last_name: 'Морозов',
      phone: '+79990000017',
    },
    {
      uid: '18',
      owner_user: '18',
      system_contact: {
        uid: '18',
        avatar: 'avatar-3.svg',
        avatar_url: '/images/avatars/avatar-3.svg',
        avatar_webp: 'avatar-3.webp',
        avatar_webp_url: '/images/avatars/avatar-3.webp',
        is_online: false,
        was_online_at: now - 14 * 86400,
      },
      first_name: 'Дарья',
      last_name: 'Никитина',
      phone: '+79990000018',
    },
    {
      uid: '19',
      owner_user: '19',
      system_contact: {
        uid: '19',
        avatar: 'avatar-4.svg',
        avatar_url: '/images/avatars/avatar-4.svg',
        avatar_webp: 'avatar-4.webp',
        avatar_webp_url: '/images/avatars/avatar-4.webp',
        is_online: false,
        was_online_at: now - 30 * 86400,
      },
      first_name: 'Кирилл',
      last_name: 'Петров',
      phone: '+79990000019',
    },
    {
      uid: '20',
      owner_user: '20',
      system_contact: {
        uid: '20',
        avatar: 'avatar-5.svg',
        avatar_url: '/images/avatars/avatar-5.svg',
        avatar_webp: 'avatar-5.webp',
        avatar_webp_url: '/images/avatars/avatar-5.webp',
        is_online: false,
        was_online_at: now - 60 * 86400,
      },
      first_name: 'Полина',
      last_name: 'Андреева',
      phone: '+79990000020',
    },
  ],
};

export const CONTACTS_LIST = [
  {
    uid: '1',
    avatar: '/images/avatars/avatar-1.svg',
    first_name: 'Влад',
    last_name: 'Ляшев',
    status: 0,
  },
  {
    uid: '2',
    avatar: '/images/avatars/avatar-2.svg',
    first_name: 'Анна',
    last_name: 'Киреева',
    status: 0.5,
  },
  {
    uid: '3',
    avatar: '/images/avatars/avatar-3.svg',
    first_name: 'Максим',
    last_name: 'Орлов',
    status: 5,
  },
  {
    uid: '4',
    avatar: '/images/avatars/avatar-4.svg',
    first_name: 'Екатерина',
    last_name: 'Смирнова',
    status: 18,
  },
  {
    uid: '5',
    avatar: '/images/avatars/avatar-5.svg',
    first_name: 'Илья',
    last_name: 'Романов',
    status: 42,
  },
  {
    uid: '6',
    avatar: '/images/avatars/avatar-1.svg',
    first_name: 'Мария',
    last_name: 'Соколова',
    status: 60,
  },
  {
    uid: '7',
    avatar: '/images/avatars/avatar-2.svg',
    first_name: 'Артём',
    last_name: 'Кузнецов',
    status: 120,
  },
  {
    uid: '8',
    avatar: '/images/avatars/avatar-3.svg',
    first_name: 'Ольга',
    last_name: 'Павлова',
    status: 300,
  },
  {
    uid: '9',
    avatar: '/images/avatars/avatar-4.svg',
    first_name: 'Денис',
    last_name: 'Фёдоров',
    status: 720,
  },
  {
    uid: '10',
    avatar: '/images/avatars/avatar-5.svg',
    first_name: 'Наталья',
    last_name: 'Иванова',
    status: 1380,
  },
  {
    uid: '11',
    avatar: '/images/avatars/avatar-1.svg',
    first_name: 'Павел',
    last_name: 'Мельников',
    status: 1440,
  },
  {
    uid: '12',
    avatar: '/images/avatars/avatar-2.svg',
    first_name: 'Юлия',
    last_name: 'Захарова',
    status: 1800,
  },
  {
    uid: '13',
    avatar: '/images/avatars/avatar-3.svg',
    first_name: 'Сергей',
    last_name: 'Белов',
    status: 2400,
  },
  {
    uid: '14',
    avatar: '/images/avatars/avatar-4.svg',
    first_name: 'Алина',
    last_name: 'Волкова',
    status: 3000,
  },
  {
    uid: '15',
    avatar: '/images/avatars/avatar-5.svg',
    first_name: 'Роман',
    last_name: 'Гусев',
    status: 4320,
  },
  {
    uid: '16',
    avatar: '/images/avatars/avatar-1.svg',
    first_name: 'Елена',
    last_name: 'Калинина',
    status: 7200,
  },
  {
    uid: '17',
    avatar: '/images/avatars/avatar-2.svg',
    first_name: 'Алексей',
    last_name: 'Морозов',
    status: 10080,
  },
  {
    uid: '18',
    avatar: '/images/avatars/avatar-3.svg',
    first_name: 'Дарья',
    last_name: 'Никитина',
    status: 20160,
  },
  {
    uid: '19',
    avatar: '/images/avatars/avatar-4.svg',
    first_name: 'Кирилл',
    last_name: 'Петров',
    status: 43200,
  },
  {
    uid: '20',
    avatar: '/images/avatars/avatar-5.svg',
    first_name: 'Полина',
    last_name: 'Андреева',
    status: 86400,
  },
];
