export const CONTACTS_LIST = [
  {
    uid: '1',
    avatar: '/images/avatars/avatar-1.svg',
    first_name: 'Влад',
    last_name: 'Ляшев',
    status: 0,
  },
  {
    uid: '2',
    avatar: '/images/avatars/avatar-2.svg',
    first_name: 'Анна',
    last_name: 'Киреева',
    status: 0.5,
  },
  {
    uid: '3',
    avatar: '/images/avatars/avatar-3.svg',
    first_name: 'Максим',
    last_name: 'Орлов',
    status: 5,
  },
  {
    uid: '4',
    avatar: '/images/avatars/avatar-4.svg',
    first_name: 'Екатерина',
    last_name: 'Смирнова',
    status: 18,
  },
  {
    uid: '5',
    avatar: '/images/avatars/avatar-5.svg',
    first_name: 'Илья',
    last_name: 'Романов',
    status: 42,
  },
  {
    uid: '6',
    avatar: '/images/avatars/avatar-1.svg',
    first_name: 'Мария',
    last_name: 'Соколова',
    status: 60,
  },
  {
    uid: '7',
    avatar: '/images/avatars/avatar-2.svg',
    first_name: 'Артём',
    last_name: 'Кузнецов',
    status: 120,
  },
  {
    uid: '8',
    avatar: '/images/avatars/avatar-3.svg',
    first_name: 'Ольга',
    last_name: 'Павлова',
    status: 300,
  },
  {
    uid: '9',
    avatar: '/images/avatars/avatar-4.svg',
    first_name: 'Денис',
    last_name: 'Фёдоров',
    status: 720,
  },
  {
    uid: '10',
    avatar: '/images/avatars/avatar-5.svg',
    first_name: 'Наталья',
    last_name: 'Иванова',
    status: 1380,
  },
  {
    uid: '11',
    avatar: '/images/avatars/avatar-1.svg',
    first_name: 'Павел',
    last_name: 'Мельников',
    status: 1440,
  },
  {
    uid: '12',
    avatar: '/images/avatars/avatar-2.svg',
    first_name: 'Юлия',
    last_name: 'Захарова',
    status: 1800,
  },
  {
    uid: '13',
    avatar: '/images/avatars/avatar-3.svg',
    first_name: 'Сергей',
    last_name: 'Белов',
    status: 2400,
  },
  {
    uid: '14',
    avatar: '/images/avatars/avatar-4.svg',
    first_name: 'Алина',
    last_name: 'Волкова',
    status: 3000,
  },
  {
    uid: '15',
    avatar: '/images/avatars/avatar-5.svg',
    first_name: 'Роман',
    last_name: 'Гусев',
    status: 4320,
  },
  {
    uid: '16',
    avatar: '/images/avatars/avatar-1.svg',
    first_name: 'Елена',
    last_name: 'Калинина',
    status: 7200,
  },
  {
    uid: '17',
    avatar: '/images/avatars/avatar-2.svg',
    first_name: 'Алексей',
    last_name: 'Морозов',
    status: 10080,
  },
  {
    uid: '18',
    avatar: '/images/avatars/avatar-3.svg',
    first_name: 'Дарья',
    last_name: 'Никитина',
    status: 20160,
  },
  {
    uid: '19',
    avatar: '/images/avatars/avatar-4.svg',
    first_name: 'Кирилл',
    last_name: 'Петров',
    status: 43200,
  },
  {
    uid: '20',
    avatar: '/images/avatars/avatar-5.svg',
    first_name: 'Полина',
    last_name: 'Андреева',
    status: 86400,
  },
];
